import os
from datetime import datetime
from typing import List
from app.models import Lead, CampaignStats
from app.services.llm_service import llm_service
from app.config import settings


class ReportGenerator:
    def __init__(self):
        self.reports_path = settings.reports_path
    
    def calculate_stats(self, leads: List[Lead]) -> CampaignStats:
        """Calculate campaign statistics from leads."""
        stats = CampaignStats()
        stats.total_leads = len(leads)
        
        for lead in leads:
            if lead.status == "contacted":
                stats.leads_contacted += 1
            if lead.status == "responded":
                stats.leads_responded += 1
            
            if lead.priority == "high":
                stats.high_priority += 1
            elif lead.priority == "medium":
                stats.medium_priority += 1
            elif lead.priority == "low":
                stats.low_priority += 1
        
        if stats.leads_contacted > 0:
            stats.response_rate = (stats.leads_responded / stats.leads_contacted) * 100
        
        return stats
    
    async def generate_report(self, leads: List[Lead]) -> str:
        """Generate a markdown campaign report with AI insights."""
        stats = self.calculate_stats(leads)
        
        # Build lead summary for AI analysis
        lead_summaries = []
        for lead in leads[:10]:  # Limit to first 10 for AI context
            lead_summaries.append(
                f"- {lead.name} ({lead.job_title} at {lead.company}): "
                f"Priority={lead.priority}, Status={lead.status}"
            )
        
        # Get AI insights
        insights_prompt = f"""Analyze this sales campaign data and provide 3-4 key insights and recommendations:

Campaign Stats:
- Total Leads: {stats.total_leads}
- Contacted: {stats.leads_contacted}
- Responded: {stats.leads_responded}
- Response Rate: {stats.response_rate:.1f}%
- High Priority: {stats.high_priority}
- Medium Priority: {stats.medium_priority}
- Low Priority: {stats.low_priority}

Sample Leads:
{chr(10).join(lead_summaries)}

Provide actionable insights for the sales team."""

        ai_insights = await llm_service.generate(
            insights_prompt,
            "You are a sales analytics expert. Provide brief, actionable insights."
        )
        
        # Build the report
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""# Sales Campaign Report

**Generated:** {timestamp}

---

## Campaign Overview

| Metric | Value |
|--------|-------|
| Total Leads | {stats.total_leads} |
| Leads Contacted | {stats.leads_contacted} |
| Leads Responded | {stats.leads_responded} |
| Response Rate | {stats.response_rate:.1f}% |

## Lead Priority Distribution

| Priority | Count | Percentage |
|----------|-------|------------|
| High | {stats.high_priority} | {(stats.high_priority/stats.total_leads*100):.1f}% |
| Medium | {stats.medium_priority} | {(stats.medium_priority/stats.total_leads*100):.1f}% |
| Low | {stats.low_priority} | {(stats.low_priority/stats.total_leads*100):.1f}% |

---

## AI-Generated Insights

{ai_insights}

---

## Lead Details

| Name | Company | Title | Priority | Score | Status |
|------|---------|-------|----------|-------|--------|
"""
        
        # Add lead rows
        for lead in leads:
            report += f"| {lead.name} | {lead.company or 'N/A'} | {lead.job_title or 'N/A'} | {lead.priority or 'N/A'} | {lead.priority_score or 'N/A'} | {lead.status} |\n"
        
        report += "\n---\n\n*Report generated by AI Sales CRM*\n"
        
        return report
    
    async def save_report(self, leads: List[Lead]) -> str:
        """Generate and save the report to a file."""
        report_content = await self.generate_report(leads)
        
        # Ensure reports directory exists
        os.makedirs(self.reports_path, exist_ok=True)
        
        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"campaign_report_{timestamp}.md"
        filepath = os.path.join(self.reports_path, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        print(f"Report saved to: {filepath}")
        return filepath


# Singleton instance
report_generator = ReportGenerator()